import type { NextPage } from 'next';
import Head from 'next/head';
import { Link } from '@/components/ui/Link';

const TopPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>UI Samples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10">
        <h1 className="font-bold text-3xl mb-8">UI Samples</h1>
        <nav>
          <h2 className="font-bold text-xl mb-4">Samples</h2>
          <ul>
            <li>
              <Link href="/samples/transition-height">Transition Height</Link>
            </li>
          </ul>
        </nav>
      </main>
    </>
  );
};

export default TopPage;
