import type { NextPage } from 'next';
import Head from 'next/head';

const TopPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hello World!</p>
    </>
  );
};

export default TopPage;
